require 'yaml'

require 'engine/game_selector.rb'

require 'engine/module/handles_yaml_files.module.rb'
require 'engine/module/parses_commands.module.rb'
require 'engine/module/uses_weapons.module.rb'
require 'engine/module/may_have_name.rb'
require 'engine/module/has_events.rb'
require 'engine/module/has_traits.rb'

require 'engine/class/game.class.rb'
require 'engine/class/game_component.class.rb'
require 'engine/class/player.class.rb'
require 'engine/class/character.class.rb'
require 'engine/class/locations.class.rb'
require 'engine/class/door.class.rb'
require 'engine/class/prop.class.rb'
require 'engine/class/cli.class.rb'
require 'engine/class/command.class.rb'
